version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."

phases:
  install:
    commands:
      - "sudo yum install -y yum-utils"
      - "sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "sudo yum -y install terraform"
  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}"
      - "ls -l"
      - "echo ## TERRAFORM APPLY"
      - "terraform destroy -var-file='./envs/env.tfvars' -auto-approve"
artifacts:
  files:  
    - '**/*'
